#define BACK -1
#define RIGHT 0
#define LEFT 1
#define FRONT 2

#define TURNING_TIME 1000
#define SELF_LENGTH_OFFSET 1000
#define MOTOR_STOP_DELAY 500

#define SAFE_DIST 10

#define IDLE 0
#define START 1
#define RUNNING 2
#define STOP 3

#define SLOT_NUM 20.0
#define WHEEL_DIAM 65.0
#define WHEELBASE 13.8

#define SLOT_NUM_FOR_DEG_ROTATION(DEGREE) (round(DEGREE / 360 * 2 * SLOT_NUM * PI * WHEELBASE / WHEEL_DIAM))
#define SIDE_TURN_SLOT_NUM SLOT_NUM_FOR_DEG_ROTATION(90)
#define BACK_TURN_SLOT_NUM SLOT_NUM_FOR_DEG_ROTATION(180)