void motorStop();
void motorLeftStop();
void motorRightStop();
void motorTurn(int direction);
void motorTurnLeft();
void motorTurnRight();
void motorTurnBack();
void motorForward(int velocity = 100);
void motorMoveOffset();
void motorLeftCounterInt();
void motorRightCounterInt();