void motorStop();
void motorLeftStop();
void motorRightStop();
void motorTurn(int direction);
void motorTurnLeft();
void motorRotateLeft(int velocity);
void motorTurnRight();
void motorRotateRight(int velocity);
void motorTurnBack();
void motorForward(int velocity = 100);
void headingVeloFix();
void motorMoveOffset();
void motorLeftCounterInt();
void motorRightCounterInt();